server:
  port: 8080
  tomcat:
    connection-timeout: 120000ms
  netty:
    connection-timeout: 120000ms

spring:
  application:
    name: api-gateway
  webflux:
    base-path: /
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            exposedHeaders:
              - Authorization
              - Content-Type
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**,/api/users/**,/api/roles/**,/api/system/**,/api/services/**
        
        - id: academic-service
          uri: lb://academic-service
          predicates:
            - Path=/api/academic/**,/api/v1/**
          filters:
            - RewritePath=/api/academic(?<segment>/?.*), /api/v1${segment}
        
        - id: syllabus-service
          uri: lb://syllabus-service
          predicates:
            - Path=/api/syllabuses/**,/api/syllabuses,/api/syllabus/**,/api/syllabus,/api/issues/**,/api/notifications/**,/api/review-comments/**,/api/syllabus/documents/**
        
        - id: workflow-service
          uri: lb://workflow-service
          predicates:
            - Path=/api/workflow/**,/api/workflows/**
        
        - id: public-service
          uri: lb://public-service
          predicates:
            - Path=/api/public/**
        
        - id: ai-service
          uri: http://ai-service:8000
          predicates:
            - Path=/api/ai/**,/ai/**
          filters:
            - RewritePath=/api/ai(?<segment>/?.*), /ai${segment}
            - RemoveResponseHeader=Access-Control-Allow-Origin
            - RemoveResponseHeader=Access-Control-Allow-Methods
            - RemoveResponseHeader=Access-Control-Allow-Headers
            - RemoveResponseHeader=Access-Control-Allow-Credentials
      
      default-filters:
        - RemoveRequestHeader=Cookie
      httpclient:
        connect-timeout: 60000
        response-timeout: 120000ms
        pool:
          type: ELASTIC
          max-idle-time: 60s
        websocket:
          max-frame-payload-length: 100000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: false
        slidingWindowSize: 100
        minimumNumberOfCalls: 100
        permittedNumberOfCallsInHalfOpenState: 30
        automaticTransitionFromOpenToHalfOpenEnabled: false
        waitDurationInOpenState: 60000
        failureRateThreshold: 99
        eventConsumerBufferSize: 10
  timelimiter:
    configs:
      default:
        cancelRunningFuture: false
        timeoutDuration: 120000

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    region: default
    avoid-url-based-aws-ec2-metadata-service: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

security:
  jwt:
    enabled: true
    secret: smdMicroservicesSecretKeyForJWTTokenGenerationAndValidation2024SuperSecureKeyWithEnoughBytesForHS512HS512HS512
    whitelist:
      - /api/auth/**
      - /api/ai/**
      - /api/workflows/**
      - /actuator/prometheus
      - /actuator/health
      - /
      # Public endpoints for guest users (no authentication required)
      - /api/v1/program
      - /api/syllabuses/public**
      - /api/syllabuses/public/**
