server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        
        - id: academic-service
          uri: lb://academic-service
          predicates:
            - Path=/api/academic/**
        
        - id: syllabus-service
          uri: lb://syllabus-service
          predicates:
            - Path=/api/syllabus/**
        
        - id: workflow-service
          uri: lb://workflow-service
          predicates:
            - Path=/api/workflow/**
        
        - id: public-service
          uri: lb://public-service
          predicates:
            - Path=/api/public/**
        
        - id: ai-service
          uri: http://ai-service:8000
          predicates:
            - Path=/api/ai/**
          filters:
            - RewritePath=/api/ai(?<segment>/?.*), $\{segment}
      
      default-filters:
        - RemoveRequestHeader=Cookie
      httpclient:
        connect-timeout: 5000
        response-timeout: 5000ms

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

security:
  jwt:
    enabled: true
    secret: smdMicroservicesSecretKeyForJWTTokenGenerationAndValidation2024
    whitelist:
      - /api/auth/**
      - /api/ai/health
      - /actuator/prometheus
      - /actuator/health
      - /
